### ISSUE TITLE
Conversation about this repo: Who, What, When, Where, Why

### ISSUE THREAD

**Issue by eldios** [NixOS/GSoC2024#2]
# Intro 

This issue is to take over the conversation from https://github.com/NixOS/foundation/issues/115 and avoid cluttering the original repo.

I guess here we can discuss all matters and decisions related to this repo.

# My suggestion and conversation startes

Here's a few small-ish ideas to get the conversation kicking:

## 1 - turn the ideas file into a directory tree

Right now the Ideas file it's just a markdown file, I think it would be better if we make it a directory, with a nice README.md file (with explanation, example, requirements, etc..) and then each new idea can be its own directory. (with a README.md file, images, code examples and all needed other artifacts)

## 2 - make the readme more "jazzy"

I'll try to make the README more colorful/enticing for possible new-comers (see an example about what I mean [HERE](https://github.com/eldios/nomad-on-docker) .. just an image or two maybe)

## 3 - create a Matrix room

We should try to foster collaboration and community as much as possible as it's at the heart of all this kind of events.
So I'm proposing we should create a few Matrix rooms like:
* #gsoc-staff:nix.org -> for the organising staff
* #gsoc-mentors:nix.org -> for the mentors and the staff
* #gsoc:nix.org -> for anybody that is interested, mentee, mentors, staff, students, curious ppl, etc..

# outro

Hopefully that's enough of a conversation starter 😬

**Comment by fricklerhandwerk** [comment]
@Eldios suggest you turn change proposals to this repo into pull requests, then they can be discussed in place. That's in your power and the fastest way to make progress. Definitely faster than waiting for anyone to pick it up. (Pro tip: just make sure it's a series of small independent changes, as those are easier to identify as obviously beneficial and accept, and possible to discuss in isolation without blocking the others.)

**Comment by eldios** [comment]
Agreed. I'll create one PR per each subpoint above.

This is more meant to be a "Decisioni record document" and conversation/debate place proposal, I guess.

**Comment by Janik-Haag** [comment]
Hey, thank you for trying to get involved!

> 1 - turn the ideas file into a directory tree

Sounds like a good idea, I would want to use a static site generator or similar with something like github pages later on so the rendered output looks a bit nicer then just the github default thing.

> 2 - make the readme more "jazzy"

knock yourself out :D

> 3 - create a Matrix room 

I'm on that. 

---

Depending on how motivated you are, you could start writing a `contributor-guidance.md` like described [here](https://developers.google.com/open-source/gsoc/help/contributor-guidance), that's still a huge to do.

**Comment by Janik-Haag** [comment]
I think the `Who, What, When, Where, Why` is pretty clear now, and am thus closing the issue now. Most of the suggestions here were also already implemented or are work in progress.
